spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: simple-library-db

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.ilpopov.otus.simple.library.mongock.ChangeLogSimpleLibrary

logging:
  level:
    root: ERROR
